### ISSUE TITLE
convert all links to archive.org, archive.md, or similar

### ISSUE THREAD

**Issue by NewAlexandria** [kdeldycke/awesome-engineering-team-management#52]
#### Summary

The links here are to line articles — which have a tendency to go offline.  For this to be a resource of long term value, link-rot can be avoided by archiving the pages. 

#### Preliminary checks

- [x] I have [read the Code of Conduct](https://github.com/kdeldycke/awesome-management/blob/main/.github/code-of-conduct.md)
- [x] I applied all rules from the [Contributing guide](https://github.com/kdeldycke/awesome-management/blob/main/.github/contributing.md)
- [x] I have checked there is not other [Issues](https://github.com/kdeldycke/awesome-management/issues) or [Pull Requests](https://github.com/kdeldycke/awesome-management/pulls) covering the same topic to open

**Comment by kdeldycke** [comment]
I have no issue replacing the original URL with an alternative archived/cached one if the original is no longer reacheable.

I agree with you, broken URLs are frustrating. But I don't think it is a good idea to replace them all. We'll do that an a case-by-case basis. If you find a broken one, please propose a PR to fix it. Or just report it as an issue and I'll do the work.

**Comment by NewAlexandria** [comment]
You can't save a tree after it's been cut down.  How are you going to archive articles that went offline?

**Comment by kdeldycke** [comment]
I see this issue as a meta-stable system:
- This list is now popular enough for its content to be picked up by archival crawlers.
- Popular content in this list are naturally archived by users who value them.
- Authors who cares about their content, or like the SEO juice this list provides, have an incentive to keep them online.

All in all, if there is no pre-existing archived copy in `archive.org` by the time the original has disappear, maybe the content wasn't worth it in the first place and not good for inclusion. Like a natural selection process on content.
