### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [kdeldycke/awesome-engineering-team-management#70]
Hi, I found some broken links:

- [x] https://ruiper.es/f746f5b7fff042c0a2565b6e36d236a4 (file: README.md, status code: 404)
- [x] https://amzn.com/B01069X4H0/?tag=kevideld-20 (file: README.md, status code: 404)
- [x] https://amzn.com/0688103804/?tag=kevideld-20 (file: README.md, error: ECONNRESET)
- [x] https://amzn.com/0679762884/?tag=kevideld-20 (file: README.md, error: ECONNRESET)
- [x] http://leadership.au.af.mil/sls-skil.htm (file: README.md, error: ENOTFOUND)
- [x] https://amzn.com/0345504194/?tag=kevideld-20 (file: README.md, status code: 404)
- [x] https://freakingrectangle.com/2022/04/15/how-to-freaking-hire-great-developers/ (file: README.md, error: EPROTO)
- [x] https://www.jarednelsen.dev/posts/The-horrifically-dystopian-world-of-software-engineering-interviews (file: README.md, status code: 404)
- [x] https://triplebyte.com/blog/fizzbuzz-2-0-pragmatic-programming-questions-for-software-engineers (file: README.md, error: ERR_TLS_CERT_ALTNAME_INVALID)
- [x] https://42hire.com/how-to-answer-the-whats-your-current-salary-job-interview-question-486254cb59ad#.izg4ips52 (file: README.md, error: ECONNRESET)
- [x] https://amzn.com/1595621113/?tag=kevideld-20 (file: README.md, error: ECONNRESET)
- [x] https://images.squarespace-cdn.com/content/v1/53419b80e4b0cccdfc3bbcf8/1579371627532-SANUEQ1REPX09L8NE1XM/ke17ZwdGBToddI8pDm48kI9Q46LYBJG1wKj9b7EvhSB7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QHyNOqBUUEtDDsRWrJLTmWp-RWlGnWD_Yv5axNBE_gjfhPXbI2t7MOi3WVleCqN9URFC-c33mY-I6dtTBVWXC/ih-cheat-sheet-v2.jpg (file: README.md, status code: 404)
- [x] https://courses.washington.edu/psii101/Powerpoints/Symptoms%20of%20Groupthink.htm (file: README.md, status code: 404)
- [x] https://amzn.com/0060845791/?tag=kevideld-20 (file: README.md, error: ECONNRESET)
- [x] https://amzn.com/0262014866/?tag=kevideld-20 (file: README.md, status code: 404)
- [x] https://florentcrivello.com/index.php/2019/09/04/the-efficiency-destroying-magic-of-tidying-up/ (file: README.md, status code: 404)
- [x] http://www.testingeducation.org/BBST/foundations/Marick_coverage.pdf (file: README.md, status code: 404)
- [x] https://www.svese.de/impact-vs-backlog-frame-in-software-development (file: README.md, error: ENOTFOUND)
- [x] https://www.cadencework.com/blog/async-standups.html (file: README.md, error: ENOTFOUND)
- [x] http://www.toomas.net/2017/07/18/reverse-engineering-a-successful-lifestyle-business-heres-everything-ive-learned-from-reading-indiehackers-com/ (file: README.md, status code: 404)
- [x] https://curatedintelligence.com/2017/10/20/kasparovs-law/ (file: README.md, error: ECONNRESET)
- [x] https://amzn.com/0132888955/?tag=kevideld-20 (file: README.md, error: ECONNRESET)
- [x] https://vimeo.com/108441214 (file: README.md, status code: 410)
- [x] http://jatins.gitlab.io/me/why-deadline/ (file: README.md, status code: 404)
- [x] https://quotes.deming.org/authors/W._Edwards_Deming/quote/2068-2 (file: README.md, status code: 404)
- [x] http://blizzard.cs.uwaterloo.ca/keshav/home/Papers/data/07/paper-reading.pdf (file: README.md, error: ECONNRESET)
- [x] https://tone-analyzer-demo.ng.bluemix.net (file: README.md, status code: 404)
- [x] https://psal.cs.drexel.edu/index.php/JStylo-Anonymouth (file: README.md, error: ECONNRESET)
- [x] http://www.jilles.net/perma/2020/06/05/presentation-rules.html (file: README.md, status code: 503)
- [x] https://amzn.com/0140280197/?tag=kevideld-20 (file: README.md, status code: 404)
- [x] https://www.cia.gov/news-information/featured-story-archive/2012-featured-story-archive/CleanedUOSSSimpleSabotage_sm.pdf (file: README.md, status code: 404)
- [x] https://www.skylyte.io/self-assessment (file: README.md, error: ENOTFOUND)
- [x] https://amzn.com/0321934113/?tag=kevideld-20 (file: README.md, status code: 404)

**Comment by kdeldycke** [comment]
Thanks @ndsvw for the report! All have been fixed upstream! :)
